# Generated by Django 3.1.2 on 2020-10-25 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insumos',
            fields=[
                ('nombreinsumo', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('precio', models.IntegerField()),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('nombre', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('apellido', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
