# Generated by Django 3.1.2 on 2020-10-27 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LavadoAutos', '0002_auto_20201027_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('cod', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=20)),
                ('imagen', models.ImageField(null=True, upload_to='Empleados')),
            ],
        ),
        migrations.CreateModel(
            name='Instalaciones',
            fields=[
                ('cod', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('direccion', models.TextField()),
                ('imagen', models.ImageField(null=True, upload_to='instalaciones')),
            ],
        ),
        migrations.CreateModel(
            name='Mision',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('cod', models.IntegerField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(upload_to='Slider')),
            ],
        ),
        migrations.CreateModel(
            name='Vision',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
