# Generated by Django 3.1.2 on 2020-10-27 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LavadoAutos', '0003_empleados_instalaciones_mision_slider_vision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instalaciones',
            name='imagen',
            field=models.ImageField(null=True, upload_to='Instalaciones'),
        ),
    ]
