# Generated by Django 3.1.2 on 2020-10-28 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LavadoAutos', '0004_auto_20201027_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumos',
            name='cod',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='insumos',
            name='nombreinsumo',
            field=models.CharField(max_length=80),
        ),
    ]
