# Generated by Django 3.1.2 on 2020-11-26 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LavadoAutos', '0005_auto_20201028_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoContacto',
            fields=[
                ('cod', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('cod', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('asunto', models.CharField(max_length=50)),
                ('mensaje', models.CharField(max_length=200)),
                ('tipoContacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LavadoAutos.tipocontacto')),
            ],
        ),
    ]
